### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]

### ISSUE THREAD

**Issue by ToPin060** [joeyk710/sample-discordjs-bot#1]
Hi,

I'm on **W11** with Node.js v18.12.1.
I was trying to debug my similar code for a few hours. Until I clone and realize that yours gives me the same error.

```
sample-bot@1.0.0 deploy
npm run build && node dist/deploy-commands.js


sample-bot@1.0.0 prebuild
npm run clean


sample-bot@1.0.0 clean
rimraf -r dist


sample-bot@1.0.0 build
tsc

node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at new NodeError (node:internal/errors:393:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
    at defaultResolve (node:internal/modules/esm/resolve:1106:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at file:///D:/.workspace/serveurs/bots/sample-discordjs-bot/dist/deploy-commands.js:19:25 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v18.12.1
```

Do you know where it could come from?

**Comment by joeyk710** [comment]
Hey @ToPin060 thanks for reporting this and I'm sorry you're having this problem. From what I have been noticing is that this happens due to a low node version, but this isn't the case. I'm going to do some testing and see what I can find. 

Even though I see that your terminal shows you using node 18.12.1, can you verify that your machine is running that version too?

**Comment by joeyk710** [comment]
Looking at the following lines below, I want you to do some testing for me to see if this works for you

https://github.com/joeyk710/sample-discordjs-bot/blob/8e4dd294ec67433aaf7a2f64f54868ac65efa69a/src/deploy-commands.ts#L7-L27

add `pathToFileURL` from this destructure of `url` on line 7
```diff
import { fileURLToPath } from 'url';
+++  import { fileURLToPath, pathToFileURL } from 'url';
```

on line 20, add the following function
```ts
const dynamicImport = (path: string) => import(pathToFileURL(path).toString()).then((module) => module.default)
```

on line 28, change the following line
```diff
const command = (await import(filePath))?.default as Command;
+++ const command = await dynamicImport(filePath) as Command;
```

I have tested this on my side, but do let me know what the outcome is

**Comment by joeyk710** [comment]
There was a pull request made - #2, which addressed the test that I suggested above. This *should* fix the issue, but please don't hesitate to let me know if you have more issues!

**Comment by ToPin060** [comment]
Hi @joeyk710,

After pulled your changes (**f0b7cf12275e86c24a33c15c4ba6a2994cfec783**)
Everything works for me, both your code and the one I had.

I really like the architecture of your project.

Thanks for yours time!
Sorry late answer by the way.

**Comment by joeyk710** [comment]
Thank you! I appreciate that a lot and don't worry about replying late, it's not a problem. I'm glad everything's working for you. Good luck on your project!
